config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jewelry_site.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jewelry_site/models.py
# STANDARD MODULE
import uuid

# THIRD PARTY MODULES
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField

# DJANGO MODULES
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.db import models


class Jewelry(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    image = models.ImageField(upload_to='images')
    description = models.TextField()
    category = models.CharField(max_length=20)
    metal = ArrayField(models.CharField(max_length=20))
    stone = ArrayField(models.CharField(max_length=20))
    care_tips = models.TextField()
    rating = models.PositiveIntegerField()
    stock = models.PositiveIntegerField()
    sold = models.PositiveIntegerField()
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def get_total(self):
        cart_items = CartItem.objects.filter(user=self.user)
        total_cost = 0
        for item in cart_items:
            total_cost = total_cost + item.get_subtotal()
        return total_cost

    def get_total_selected(self):
        cart_items = CartItem.objects.filter(cart=self, is_selected=True)
        total_cost = 0
        for item in cart_items:
            total_cost = total_cost + item.get_subtotal()
        return total_cost

    def __str__(self):
        return self.user.username


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    jewelry = models.ForeignKey(Jewelry, on_delete=models.CASCADE)
    order_quantity = models.PositiveIntegerField()
    is_selected = models.BooleanField(default=True)

    def get_subtotal(self):
        return self.jewelry.price * self.order_quantity

    def __str__(self):
        return self.jewelry.name


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address_line_1 = models.CharField(max_length=100, null=True, blank=True)
    address_line_2 = models.CharField(max_length=100, null=True, blank=True)
    admin_area_1 = models.CharField(max_length=100, null=True, blank=True)
    admin_area_2 = models.CharField(max_length=100, null=True, blank=True)
    country = CountryField()
    postal_code = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        if self.address_line_2:
            return self.address_line_1 + self.address_line_2 + self.admin_area_1 + self.admin_area_2 + self.country.name + self.postal_code
        else:
            return self.address_line_1 + self.admin_area_1 + self.admin_area_2 + self.country.name + self.postal_code


class ContactDetail(models.Model):
    phone_number = PhoneNumberField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=100)
    address = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    total_paid = models.DecimalField(max_digits=10, decimal_places=2)
    order_key = models.CharField(max_length=200)
    payment_option = models.CharField(max_length=200, blank=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return str(self.created)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    jewelry = models.ForeignKey(Jewelry, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)


class RequestID(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    def __str__(self):
        return self.id

templates/about.html
{% block extrahead %}
    {% load static %}
    <meta name="description"
          content="Collection of all jewelries in Elma's Jewels" />
    <link rel="stylesheet" href="{% static 'css/all.css' %}" />
    <title>ELMA'S JEWELS | ABOUT PAGE</title>
{% endblock %}
{% block content %}
    {% include 'partials/header.html' %}
    <h1>ABOUT</h1>
    {% include 'partials/footer.html' %}
{% endblock %}

templates/add_address.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}
    <meta name="description" content="Elma's Jewels Home Page" />
    <link rel="stylesheet" href="{% static 'css/all.css' %}" />
    <link rel="stylesheet" href="{% static 'css/profile.css' %}" />
    <title>ELMA'S JEWELS | HOME</title>
{% endblock %}
{% block content %}
    {% include 'partials/header2.html' %}
    <main>
        <form action="{% url 'add_address' %}" method="post">
            {% csrf_token %}
            <section>
                <h3>Account Details</h3>
                <div>
                    <label for="id_address_line_1">address_line_1</label>
                    {{ address_form.address_line_1 }}
                </div>
                <div>
                    <label for="id_address_line_2">address_line_2</label>
                    {{ address_form.address_line_2 }}
                </div>
                <div>
                    <label for="id_admin_area_2">admin_area_2</label>
                    {{ address_form.admin_area_2 }}
                </div>
                <div>
                    <label for="id_admin_area_1">admin_area_1</label>
                    {{ address_form.admin_area_1 }}
                </div>
                <div>
                    <label for="id_postal_code">postal_code</label>
                    {{ address_form.postal_code }}
                </div>
                <div>
                    <label for="id_country">Country</label>
                    {{ address_form.country }}
                </div>
            </section>
            <section>
                <div>
                    <button type="submit">add address</button>
                </div>
            </section>
        </form>
    </main>
    {% include 'partials/footer.html' %}
    <script src="{% static 'js/header.js' %}"></script>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="author" content="James Tito" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
            href="https://fonts.googleapis.com/css2?family=Passions+Conflict&family=Sen&display=swap"
            rel="stylesheet"
        />
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
        <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>

        {% block extrahead %} {% endblock %}
    </head>
    <body>
        {% block content %} {% endblock %}
    </body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
<!-- ### -->
{% block extrahead %}
    <meta name="description" content="Elma's Jewels Cart" />
    <link rel="stylesheet" href="{% static 'css/all.css' %}" />
    <link rel="stylesheet" href="{% static 'css/cart.css' %}" />
    <title>ELMA'S JEWEL | CART</title>
{% endblock %}
{% block content %}
    {% include 'partials/header2.html' %}
    <main id="cart-section">
        <h2>CART</h2>
        {% include 'partials/alerts.html' %}
        <br />
        <ul id="cart-list">
            <li id="cart-header">
                <!-- <span class="cart-checkbox"><input class="checkbox" name="checkbox" type="checkbox" checked="true" /></span> -->
                <span class="cart-item">ITEM</span>
                <span class="cart-price">PRICE</span>
                <span class="cart-quantity">QUANTITY</span>
                <span class="cart-total">TOTAL</span>
            </li>
            <hr />
            {% if cart_items|length > 0 %}
                {% for cart_item in cart_items %}
                    <li class="cart-items">
                        <form class="cart-checkbox"
                              method="post"
                              action="/cart/toggle_checkbox/{{ cart_item.id }}">
                            {% csrf_token %}
                            {% if cart_item.is_selected == True %}
                                <input class="checkbox"
                                       name="checkbox"
                                       type="checkbox"
                                       checked="true"
                                       value="{{ cart_item.id }}" />
                            {% else %}
                                <input class="checkbox"
                                       name="checkbox"
                                       type="checkbox"
                                       value="{{ cart_item.id }}" />
                            {% endif %}
                        </form>
                        <figure class="cart-item">
                            <img src="{{ cart_item.jewelry.image.url }}" alt="" />
                            <figcaption>{{ cart_item.jewelry.name }}</figcaption>
                        </figure>
                        <div class="cart-price">
                            <span>Price:</span>
                            $ {{ cart_item.jewelry.price|intcomma }}
                        </div>
                        <div class="cart-quantity">
                            <span>Quantity:</span>
                            <form action="/cart/update_cart_item/{{ cart_item.id }}"
                                  class="update-order-quantity-form"
                                  method="post">
                                {% csrf_token %}
                                <button class="fas fa-angle-up"></button>
                                <input type="number"
                                       min="0"
                                       value="{{ cart_item.order_quantity }}"
                                       name="order-quantity" />
                                <button class="fas fa-angle-down"></button>
                            </form>
                            <form action="/cart/delete_cart_item/{{ cart_item.id }}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="fas fa-trash-alt"></button>
                            </form>
                        </div>
                        <div class="cart-total">
                            <span>Total:</span>
                            $ {% widthratio cart_item.jewelry.price 1 cart_item.order_quantity as total %} {{ total | intcomma }}
                        </div>
                    </li>
                    <hr />
                {% endfor %}
            {% else %}
                <p>NO ITEMS IN CART</p>
            {% endif %}
        </ul>
        <form id="cart-checkout-section" action="{% url 'checkout' %}" method="get">
            <div>
                <label>Add Order Note</label>
                <textarea name="" id="" cols="30" rows="10"></textarea>
            </div>
            <div>
                <p>
                    <span>SUBTOTAL:</span><strong>$ {{ total_cost | intcomma }}</strong>
                </p>
                <p>
                    <em>Shipping & taxes calculated at checkout.</em>
                </p>
                <button type="submit">
                    <i class="fas fa-shopping-bag"> </i> CHECKOUT
                </button>
            </div>
        </form>
    </main>
    {% include 'partials/footer.html' %}
    <script src="{% static 'js/header.js' %}"></script>
    <script src="{% static 'js/cart.js' %}"></script>
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block extrahead %}
    <meta name="description" content="Elma's Jewels Checkout Page" />
    <link rel="stylesheet" href="{% static 'css/all.css' %}" />
    <link rel="stylesheet" href="{% static 'css/checkout.css' %}" />
    <title>ELMA'S JEWEL | CHECKOUT</title>
{% endblock %}
{% block content %}
    {% include 'partials/header2.html' %}
    <main>
        <h2>CHECKOUT</h2>
        <form action="">
            {% csrf_token %}
            <section id="order-summary-section">
                <h3>Order Summary:</h3>
                <ul>
                    <li>
                        <div class="checkout-item">
                            <strong>Item</strong>
                        </div>
                        <div class="checkout-quantity">
                            <strong>Qty</strong>
                        </div>
                        <div class="checkout-price">
                            <strong>Price</strong>
                        </div>
                    </li>
                    {% for checkout_item in checkout_items %}
                        <li class="checkout-items">
                            <figure class="checkout-item">
                                <img src="{{ checkout_item.jewelry.image.url }}" alt="" />
                                <figcaption>{{ checkout_item.jewelry.name }}</figcaption>
                            </figure>
                            <div class="checkout-quantity">
                                <span>{{ checkout_item.order_quantity }}</span>
                            </div>
                            <div class="checkout-price">$ {{ checkout_item.jewelry.price | intcomma }}</div>
                        </li>
                    {% endfor %}
                </ul>
                <hr />
                <div id="total-cost-container">
                    <strong>Total:</strong><strong>$ {{ total_cost | intcomma }}</strong>
                    <input type="hidden" id="total-cost" value="{{ total_cost }}" />
                </div>
            </section>
            <section id="submit-checkout-section">
                <div id="paypal-button-container"></div>
                <!-- <button type="submit">Checkout</button> -->
            </section>
        </form>
    </main>
    {% include 'partials/footer.html' %}
    <script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== "") {
            var cookies = document.cookie.split(";");
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === name + "=") {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie("csrftoken");
    </script>
    <script src="https://www.paypal.com/sdk/js?client-id=AeiH3JAE3-OIIJz0b5KQvVXrzBGhn15fsBt-XtGMTBcVQtnrRa8nwBpwPHv2LUjwvc69w5oW3B8uUIqx&disable-funding=paylater"></script>
    <script>
    // Render the PayPal button into #paypal-button-container
    paypal
        .Buttons({
            // Call your server to set up the transaction
            createOrder: function (data, actions) {
                return fetch("{% url 'create_order' %}", {
                    method: "post",
                    headers: {
                        "Content-Type": "application/json",
                        "X-CSRFToken": csrftoken,
                    },
                })
                    .then(function (res) {
                        return res.json();
                    })
                    .then(function (orderData) {
                        return orderData.id;
                    });
            },

            // Call your server to finalize the transaction
            onApprove: function (data, actions) {
                console.log("hellooooooooo0000000000000000000000000000000000000000000");
                return fetch("/checkout/payment_complete/" + data.orderID, {
                    method: "post",
                    headers: {
                        "Content-Type": "application/json",
                        "X-CSRFToken": csrftoken,
                    },
                })
                    .then(function (res) {
                        return res.json();
                    })
                    .then(function (orderData) {
                        // Three cases to handle:
                        //   (1) Recoverable INSTRUMENT_DECLINED -> call actions.restart()
                        //   (2) Other non-recoverable errors -> Show a failure message
                        //   (3) Successful transaction -> Show confirmation or thank you

                        // This example reads a v2/checkout/orders capture response, propagated from the server
                        // You could use a different API or structure for your 'orderData'
                        var errorDetail = Array.isArray(orderData.details) && orderData.details[0];

                        if (errorDetail && errorDetail.issue === "INSTRUMENT_DECLINED") {
                            return actions.restart(); // Recoverable state, per:
                            // https://developer.paypal.com/docs/checkout/integration-features/funding-failure/
                        }

                        if (errorDetail) {
                            var msg = "Sorry, your transaction could not be processed.";
                            if (errorDetail.description) msg += "\n\n" + errorDetail.description;
                            if (orderData.debug_id) msg += " (" + orderData.debug_id + ")";
                            return alert(msg); // Show a failure message (try to avoid alerts in production environments)
                        }

                        // Successful capture! For demo purposes:
                        location.href = "{% url 'profile' %}";

                        // Replace the above to show a success message within this page, e.g.
                        // const element = document.getElementById('paypal-button-container');
                        // element.innerHTML = '';
                        // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                        // Or go to another URL:  actions.redirect('thank_you.html');
                    });
            },
        })
        .render("#paypal-button-container");
    </script>
    <script src="{% static 'js/header.js' %}"></script>
{% endblock %}

templates/contact.html
{% block extrahead %}
    {% load static %}
    <meta name="description"
          content="Collection of all jewelries in Elma's Jewels" />
    <link rel="stylesheet" href="{% static 'css/all.css' %}" />
    <title>ELMA'S JEWELS | CONTACT US</title>
{% endblock %}
{% block content %}
    {% include 'partials/header.html' %}
    <h1>CONTACT</h1>
    {% include 'partials/footer.html' %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block extrahead %}
    <meta name="description" content="Elma's Jewels Home Page" />
    <link rel="stylesheet" href="{% static 'css/all.css' %}" />
    <title>ELMA'S JEWELS | HOME</title>
{% endblock %}
{% block content %}
    {% include 'partials/header.html' %}
    <main>
        <section id="categories-section">
            <h2>CATEGORIES</h2>
            <div>
                <a href="/shop?category=rings" method="get">
                    <figure>
                        <img src="{% static 'images/others/kateryna-hliznitsova-orila32ay5U-unsplash.jpg' %}"
                             alt="" />
                        <figcaption>RINGS</figcaption>
                    </figure>
                </a>
                <a href="/shop?category=necklaces" method="get">
                    <figure>
                        <img src="{% static 'images/others/andie-gomez-acebo-sEq4onJnWrI-unsplash.jpg' %}"
                             alt="" />
                        <figcaption>NECKLACES</figcaption>
                    </figure>
                </a>
                <a href="/shop?category=earrings" method="get">
                    <figure>
                        <img src="{% static 'images/others/patricia-zavala-3tP-noTcaE8-unsplash.jpg' %}"
                             alt="" />
                        <figcaption>EARRINGS</figcaption>
                    </figure>
                </a>
                <a href="/shop?category=bracelets" method="get">
                    <figure>
                        <img src="{% static 'images/others/sama-hosseini-h_ssRPj8UZo-unsplash.jpg' %}"
                             alt="" />
                        <figcaption>BRACELETS</figcaption>
                    </figure>
                </a>
            </div>
        </section>
        <section id="best-sellers-section">
            <h2>BEST SELLERS</h2>
            <ul>
                {% for best_seller in best_sellers %}
                    <li>
                        <article>
                            <a href="/shop/jewelry/{{ best_seller.id }}">
                                <img src="{{ best_seller.image.url }}" alt="" />
                                <h3>{{ best_seller.name }}</h3>
                                <p>
                                    <data value="{{ best_seller.price }}">$ {{ best_seller.price | intcomma }}</data>
                                </p>
                            </a>
                        </article>
                    </li>
                {% endfor %}
            </ul>
            <div>
                <a id="view-all-btn" href="shop">VIEW ALL</a>
            </div>
        </section>
    </main>
    {% include 'partials/footer.html' %}
    <script src="{% static 'js/header.js' %}"></script>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}
    <meta name="description" content="Elma's Jewels Home Page" />
    <link rel="stylesheet" href="{% static 'css/all.css' %}" />
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
    <title>ELMA'S JEWELS | HOME</title>
{% endblock %}
{% block content %}
    {% include 'partials/header2.html' %}
    <main>
        <h2>Login</h2>
        {% include 'partials/alerts.html' %}
        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" id="username" name="username" />
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" />
            </div>
            <div>
                <button type="submit">Login</button>
                <a href="{% url 'register' %}">Create an Account</a>
            </div>
        </form>
    </main>
    {% include 'partials/footer.html' %}
    <script src="{% static 'js/header.js' %}"></script>
{% endblock %}

templates/payment.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        {{ form.render }}
    </body>
</html>

templates/product.html
{% extends 'base.html' %} {% load static %}
<!-- #### -->

{% block extrahead %}
<meta name="description" content="Collection of all jewelries in Elma's Jewels" />
<link rel="stylesheet" href="{% static 'css/all.css' %}" />
<link rel="stylesheet" href="{% static 'css/product.css' %}" />
<link rel="stylesheet" href="{% static 'css/cart.css' %}" />
<title>ELMA'S JEWELS | ALL JEWELRY</title>
{% endblock %}
<!-- #### -->

{% block content %}
<!-- #### -->
{% include 'partials/header.html' %}
<main>
    <section id="product-section">
        <figure>
            <img src="{{ product.image.url }}" alt="" />
            <figcaption></figcaption>
        </figure>

        <h2>{{ product.name }}</h2>
        <div>
            <strong><data class="price">$ {{ product.price }}</data></strong>
        </div>
        <form action="/cart/add_to_cart/{{ product.id }}" method="post">
            {% csrf_token %}
            <button type="submit">ADD TO CART</button>
        </form>
        <p>{{ product.description }}</p>
        <aside>
            <h3>CARE TIPS</h3>
            <p>{{ product.care_tips }}</p>
        </aside>
    </section>
    <section id="product-review-section">
        <h2>CUSTOMER REVIEWS</h2>
        <div id="{{ product.rating }}">
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star checked"></span>
            <span class="fa fa-star"></span>
            <span class="fa fa-star"></span><br />
            <em>Based on 7 reviews</em>
        </div>
        <ul id="rating-statistics">
            <li>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span>0%</span>
                <span>(0)</span>
            </li>
            <li>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span>0%</span>
                <span>(0)</span>
            </li>
            <li>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                <span>100%</span>
                <span>(7)</span>
            </li>
            <li>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                <span>0%</span>
                <span>(0)</span>
            </li>
            <li>
                <span class="fa fa-star checked"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                <span>0%</span>
                <span>(0)</span>
            </li>
        </ul>

        <ul id="reviews">
            <li>
                <span>James</span> <br />
                <time datetime="2022-7-7">07/07/2022</time>
                <div class="rating">
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span><br />
                </div>
                <br />
                <p>
                    Just received both items, I love love love them! Thank you so much for your
                    service and the gift. Will highly recommend your brand to all of my friends.
                </p>
            </li>
            <li>
                <span>James</span> <br />
                <time datetime="2022-7-7">07/07/2022</time>
                <div class="rating">
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span><br />
                </div>
                <br />
                <p>
                    Just received both items, I love love love them! Thank you so much for your
                    service and the gift. Will highly recommend your brand to all of my friends.
                </p>
            </li>
            <li>
                <span>James</span> <br />
                <time datetime="2022-7-7">07/07/2022</time>
                <div class="rating">
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span><br />
                </div>
                <br />
                <p>
                    Just received both items, I love love love them! Thank you so much for your
                    service and the gift. Will highly recommend your brand to all of my friends.
                </p>
            </li>
            <li>
                <span>James</span> <br />
                <time datetime="2022-7-7">07/07/2022</time>
                <div class="rating">
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span><br />
                </div>
                <br />
                <p>
                    Just received both items, I love love love them! Thank you so much for your
                    service and the gift. Will highly recommend your brand to all of my friends.
                </p>
            </li>
        </ul>
    </section>
</main>
{% include 'partials/footer.html' %}
<!-- #### -->
{% endblock %}

templates/shipping.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <header>SHIPPING</header>
        <main>
            <form action="">
                <div>
                    <div>Contact: <span>example@gmail.com</span></div>
                    <div>Ship To: <span>Gredu, Panabo, Davao del Norte, Philippines</span></div>
                </div>
                <div>
                    Shipping Method:
                    <div>
                        <input type="radio" />
                        <label for="">Free Shipping</label>
                    </div>
                    <div>
                        <input type="radio" />
                        <label for="">Expedited</label>
                    </div>
                </div>
                <button>Continue to Payment</button>
            </form>
        </main>
    </body>
</html>